name: Continuous Integration
on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Install Python 3
        uses: actions/setup-python@v1
        with:
          python-version: 3.9
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install .[dev]
  test:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - run: python -m unittest
  format:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - run: python -m black . --check
  lint:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - run: flake8 --extend-ignore=W503
