name: Continuous Integration
on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Install Python 3
        uses: actions/setup-python@v1
        with:
          python-version: 3.9
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install .
  test:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - run: python -m unittest
  format:
    runs-on: ubuntu-latest
    steps:
      - uses: psf/black@stable
        with:
          options: "--check --verbose"
          version: "22.1.0"
  lint:
    runs-on: ubuntu-latest
    steps:
      - run: pip install flake8
      - run: flake8
